[repos]
personal = "~/Documents/repos/personal"
work = "~/Documents/repos/work"

[packages]
core = [
  "git", "fish", "tailscale", "sshfs", "wl-clipboard",
  "curl", "unzip", "rpmextract", "neovim", "github-cli",
  "visual-studio-code-bin", "docker-desktop", "antigravity",
  "claude-code", "gemini-cli", "fish-nvm",
  "ollama", "qwen-code"
]

[packages.choice]
aws = ["aws-cli-v2", "aws-cli"]
opencode = ["opencode", "opencode-bin"]
openai-codex = ["openai-codex", "openai-codex-bin"]

[packages.mac]
core = [
  "git", "fish", "gh", "neovim", "curl", "unzip",
  "ollama", "gemini-cli", "opencode"
]
casks = [
  "docker-desktop", "claude-code", "visual-studio-code"
]

[packages.mac.choice]
aws = ["awscli"]
